CREATE table orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  total_price DECIMAL(10, 2) NOT NULL,
  stripe_session_id VARCHAR(255),
  status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '0:未払い, 1:支払済み, 2:キャンセル, 3:返金処理中, 4:返金済み',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);